### ISSUE TITLE
Use Whiteboard to filter bugs for teams

### ISSUE THREAD

**Issue by adambkaplan** [openshift/bugzilla-tools#6]
The `openshift-controller-manager` Bugzilla component is shared between the Build API and Workloads teams. By default bugs belonging to ocm are owned by the Build API team. However if "workloads" is added to the internal whiteboard, that bug is the responsibility of the Workloads team.

How can we address this in the configuration?

/cc @soltysh

**Comment by eparis** [comment]
Other teams inside OpenShift use subcomponents to split components. dpp can get subcomponents created in bugzilla. They need to know the name, default assignee, default qa assignee and 1 sentence description for each new subcomponent.

After they create a subcomponent you will need to mess set the subcomponent on all open bugs. When the first subcompoent is create it becomes invalid to not have a subcomponent though nothing will automatically add one to open bugs. Bugs in this invalid state will be unable to be updated in any way.

After you get subcomponents created you can check out https://github.com/openshift/li/blob/master/tools/shiftzilla/subcomponent_teams.yaml to configure your 2 teams.

I do not plan to implement splitting by whiteboard at this time.
